import '@/styles/globals.css'
import Providers from '@/components/Providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import Login from '@/components/Login'
import Home from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (

    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {!session? <Login/> : <Home/>}
          {children}
        </Providers>
      </body>

    </html>
  )
}
